# Generated by Django 4.2.7 on 2023-11-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=50)),
                ('phnumber', models.CharField(max_length=13)),
            ],
        ),
    ]
